//===-- XTenNNOps.td - XTenNN Python Binding Ops definitions *- tablegen -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//

// (c) Copyright 2023 - 2024 Advanced Micro Devices, Inc. All Rights reserved.

//
//===----------------------------------------------------------------------===//

#ifndef PYTHON_BINDINGS_XTENNN_OPS
#define PYTHON_BINDINGS_XTENNN_OPS

include "xten/Dialect/XTenNN/IR/XTenNNOps.td"

#endif
